### ISSUE TITLE
how to use mysql/mariadb?

### ISSUE THREAD

**Issue by sottolski** [alsutton/enterprisepasswordsafe#30] opened 2020-08-21 12:20 UTC
I tried with adding

'org.mariadb.jdbc:mariadb-java-client:2.6.2'

as runtime dependency to build.gradle, (just under the derbytools) and setting

EPS_DATABASE_TYPE="MariaDB"
EPS_JDBC_DRIVER_CLASS="org.mariadb.jdbc.DriverManager"

I tried several variations of mysql vs. mariadb or Driver vs. DriverManager, but always get something like

`1-Aug-2020 12:15:19.442 SEVERE [http-nio-8080-exec-7] com.enterprisepasswordsafe.ui.web.servlets.VerifyJDBCConfiguration.doGet Error setting JDBC configuration
        java.lang.ClassNotFoundException: "org.mariadb.jdbc.DriverManager"
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)`

Thanks

Sascha

**Comment by sottolski** [comment] 2020-08-23 20:42
That's what I did, but still get the class not found exception.

Thanks

Sascha 

Am 23. August 2020 11:56:06 MESZ schrieb Al Sutton <notifications@github.com>:
>The docker image is currently only built with support for derby. To add
>support for another database you will need to add a dependency on the
>JDBC driver for that database. 
>
>The derby dependency is declared
>[here](https://github.com/alsutton/enterprisepasswordsafe/blob/main/build.gradle#L33),
>so you can replace that, or add, the JDBC driver dependency for the
>database of your choice.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alsutton/enterprisepasswordsafe/issues/30#issuecomment-678753898

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by alsutton** [comment] 2020-08-24 06:09
Can you create a pull request with your changes so I can see what you've done and test the changes on my machine.

**Comment by sottolski** [comment] 2020-08-24 09:09
Thanks Al,

I apparently still need to learn how to create pull requests, but my change is somewhat tiny:

`diff --git a/build.gradle b/build.gradle
index 7069362..071c427 100644
--- a/build.gradle
+++ b/build.gradle
@@ -31,7 +31,8 @@ dependencies {
     runtime         'opensymphony:sitemesh:2.4.2',
                     'javax.servlet:jstl:1.2',
                     'org.apache.derby:derby:10.15.2.0',
-                    'org.apache.derby:derbytools:10.15.2.0'
+                    'org.apache.derby:derbytools:10.15.2.0',
+                    'org.mariadb.jdbc:mariadb-java-client:2.5.4'
 
     tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",
             "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatVersion}",
@@ -67,4 +68,4 @@ jacocoTestReport {
         csv.enabled false
         html.destination file("${buildDir}/reports/coverage")
     }
-}`

Tried the latest 2.6.2 as well to no avail. For the docker run, I did

`docker run -it --rm -p 8888:8080 --env-file env.file eps:latest`

with env.file as

`EPS_DATABASE_TYPE="MySQL"
EPS_JDBC_DRIVER_CLASS="org.mariadb.jdbc.Driver"
EPS_JDBC_URL="jdbc:mysql://localhost/passwordsafe"
EPS_DATABASE_USERNAME="user"
EPS_DATABASE_PASSWORD="pass"`

I also tried `org.mariadb.jdbc.DriverManager`, but same class not found exception occurs.

If I exec in to the docker container, the lib seems to be there, though.

As a side note, what I want to try is running the container against the copy of an oldish production EPS 1.58. Although I almost expect that the schema probably is not compatible.

Thanks a lot

Sascha

**Comment by alsutton** [comment] 2020-08-24 10:38
Looking at the [MariaDB docs](https://mariadb.com/kb/en/about-mariadb-connector-j/#java-compatibility), the 2.6 drivers would seem to be the best fit (this project uses Java 11).

Are you [rebuilding the docker image](https://github.com/alsutton/enterprisepasswordsafe#running-the-eps) after the change? I've [created a pull request](https://github.com/alsutton/enterprisepasswordsafe/pull/36) which adds MariaDB to the image and after rebuilding and running the image I get the following, expected, error;

```
        java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Socket fail to connect to host:localhost, port:3306. Connection refused (Connection refused)
                at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
                at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1243)
                at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:622)
                at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:142)
                at org.mariadb.jdbc.Driver.connect(Driver.java:86)
...
```

(it's expected because I don't use MariaDB)

**Comment by sottolski** [comment] 2020-08-24 11:33
Hi Al,

thanks so much for looking it. It remains mysterious; just tried your branch, but the error remains the same for me :-(

yes, I did rebuild the docker image, and I see the maria jar file if I exec into the running container:

```
# docker exec -ti crazy_darwin /bin/bash
root@bb35561c0309:/usr/local/tomcat# ls -l webapps/ROOT/WEB-INF/lib/mariadb-java-client-2.5.4.jar 
-rw-r----- 1 root root 616389 Aug 21 17:59 webapps/ROOT/WEB-INF/lib/mariadb-java-client-2.5.4.jar
```

I did even unzipped the jar file to verify that the class is in the .jar (after apt update; apt install unzip)

```
root@bb35561c0309:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib# unzip -l mariadb-java-client-2.5.4.jar |grep Driver
     2556  2020-01-27 14:45   META-INF/services/java.sql.Driver
     4598  2020-01-27 14:46   org/mariadb/jdbc/Driver.class
```

here's the full log from the commandline, the exception is thrown on first access of localhost:8888

```
[sottolski@w304658 enterprisepasswordsafe (add_mariadb)]$ sudo docker run -it --rm -p 8888:8080 --env-file env.file eps:latest
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-11
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
24-Aug-2020 11:19:03.427 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.35
24-Aug-2020 11:19:03.432 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 5 2020 20:36:20 UTC
24-Aug-2020 11:19:03.432 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.35.0
24-Aug-2020 11:19:03.432 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
24-Aug-2020 11:19:03.432 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-42-generic
24-Aug-2020 11:19:03.433 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
24-Aug-2020 11:19:03.433 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
24-Aug-2020 11:19:03.433 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.7+10
24-Aug-2020 11:19:03.433 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
24-Aug-2020 11:19:03.433 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
24-Aug-2020 11:19:03.433 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
24-Aug-2020 11:19:03.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
24-Aug-2020 11:19:03.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
24-Aug-2020 11:19:03.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
24-Aug-2020 11:19:03.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
24-Aug-2020 11:19:03.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
24-Aug-2020 11:19:03.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
24-Aug-2020 11:19:03.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
24-Aug-2020 11:19:03.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
24-Aug-2020 11:19:03.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
24-Aug-2020 11:19:03.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
24-Aug-2020 11:19:03.453 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
24-Aug-2020 11:19:03.453 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
24-Aug-2020 11:19:03.453 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.24] using APR version [1.6.5].
24-Aug-2020 11:19:03.453 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
24-Aug-2020 11:19:03.453 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
24-Aug-2020 11:19:03.462 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
24-Aug-2020 11:19:03.837 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
24-Aug-2020 11:19:03.876 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [701] milliseconds
24-Aug-2020 11:19:03.935 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
24-Aug-2020 11:19:03.935 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.35]
24-Aug-2020 11:19:03.954 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
24-Aug-2020 11:19:05.617 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
24-Aug-2020 11:19:05.681 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [1,727] ms
24-Aug-2020 11:19:05.688 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
24-Aug-2020 11:19:05.700 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1,823] milliseconds
24-Aug-2020 11:19:15.039 SEVERE [http-nio-8080-exec-7] com.enterprisepasswordsafe.ui.web.servlets.VerifyJDBCConfiguration.doGet Error setting JDBC configuration
        java.lang.ClassNotFoundException: "org.mariadb.jdbc.Driver"
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
                at java.base/java.lang.Class.forName0(Native Method)
                at java.base/java.lang.Class.forName(Class.java:315)
                at com.enterprisepasswordsafe.database.dbpool.DatabasePool.<init>(DatabasePool.java:45)
                at com.enterprisepasswordsafe.database.dbpool.DatabasePoolFactory.initialise(DatabasePoolFactory.java:34)
                at com.enterprisepasswordsafe.database.dbpool.DatabasePoolFactory.setConfiguration(DatabasePoolFactory.java:43)
                at com.enterprisepasswordsafe.ui.web.servlets.VerifyJDBCConfiguration.isExistingConnectionInformationValid(VerifyJDBCConfiguration.java:88)
                at com.enterprisepasswordsafe.ui.web.servlets.VerifyJDBCConfiguration.doGet(VerifyJDBCConfiguration.java:52)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
                at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.enterprisepasswordsafe.ui.web.servletfilter.DatabaseCleanupFilter.doFilter(DatabaseCleanupFilter.java:54)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.enterprisepasswordsafe.ui.web.servletfilter.ErrorCatcherFilter.doFilter(ErrorCatcherFilter.java:56)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.enterprisepasswordsafe.ui.web.servletfilter.WelcomeFilter.doFilter(WelcomeFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.enterprisepasswordsafe.ui.web.servletfilter.HeaderParameterFilter.doFilter(HeaderParameterFilter.java:91)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.enterprisepasswordsafe.ui.web.servletfilter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:43)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
```

Best

Sascha

**Comment by sottolski** [comment] 2020-08-24 11:50
update: it DOES work if I put the parameters into the Dockerfile.

If I put the same values as "--env-file env.file" I get the class not found.

**Comment by sottolski** [comment] 2020-08-24 13:35
Just in case it helps someone else: For now it only works if I put the environment variables in the Dockerfile and rebuild the docker image. Passing them via --env-file did not work for me.

For my setup, to connect to mysql on localhost I really needed to connect to the docker host, that is, 172.17.0.1.

As expected, it does not work to use the DB from our god old EPS ("Unknown column 'appusers.user_pass_b' in 'field list'"), but that obviously is a different matter.

Again, thanks for your assistance!

Sascha

**Comment by sottolski** [comment] 2020-08-24 14:15
Sorry for another remark, to make "Initialize Database" work I had to

```
diff --git a/src/main/java/com/enterprisepasswordsafe/database/vendorspecific/implementations/MysqlDAL.java b/src/main/java/com/enterprisepasswordsafe/database/vendorspecific/implementations/MysqlDAL.java
index 3e4522b..01454c7 100644
--- a/src/main/java/com/enterprisepasswordsafe/database/vendorspecific/implementations/MysqlDAL.java
+++ b/src/main/java/com/enterprisepasswordsafe/database/vendorspecific/implementations/MysqlDAL.java
@@ -34,7 +34,7 @@ public class MysqlDAL
        {
                super();
 
-               translationMap.put( ColumnSpecification.TYPE_LONG, "LONG" );
+               translationMap.put( ColumnSpecification.TYPE_LONG, "BIGINT" );
                translationMap.put( ColumnSpecification.TYPE_INT, "INT" );
                translationMap.put( ColumnSpecification.TYPE_CHAR, "CHAR" );
                translationMap.put( ColumnSpecification.TYPE_ID, "VARCHAR(20)" );
```

not sure if this really is a proper fix, but before I got 

`org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: BLOB/TEXT column 'dt_l' used in key specification without a key length`

**Comment by alsutton** [comment] 2020-08-25 07:09
Thanks for the information. 

I've confirmed setting a value on the command line with `-e` or `--env-file` works on the version of docker I'm using (19.03.12) by doing the following;

1. Build the docker image
2. Run `docker run -it --rm -p 8888:8080 -e EPS_DATABASE_TYPE=XXXX eps:latest env`
3 Verify `EPS_DATABASE_TYPE` is shown as having the value XXXX

For step 2 you can replace`-e EPS_DATABASE_TYPE=XXXX` with `--env-file env.file` to test env files, so I'm wondering if there's a local configuration issue which caused the problem.

**Comment by alsutton** [comment] 2020-08-25 07:14
Looking at the MySQL page it looks like `LONG` isn't a supported type as of today, so I've made a pull request from your change and merged it in.

**Closed** 2020-08-25 07:14 UTC
Labels: question

**Comment by sottolski** [comment] 2020-08-25 08:50
Hi,

thanks a for testing it, I found my mistake: I had

`EPS_DATABASE_TYPE="XXXX"`

in my env.file, I wasn't aware that quotes are being passed as is.

Best

Sascha
